import { Nav } from "./components";
import "./globals.scss";
import { Nunito } from "next/font/google";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Dealintent</title>
      </head>
      <body className={inter.className}>
        <Nav />
        <div className="layout-container">{children}</div>
      </body>
    </html>
  );
}
